#!/bin/sh

# presetup:
# setup wifi: sudo apt-get install wicd-curses
# http://www.raspyfi.com/wi-fi-on-raspberry-pi-a-simple-guide/
# clone this repo

sudo apt-get install matchbox
sudo apt-get install x11-xserver-utils
sudo apt-get install unclutter
sudo apt-get install midori

#create start up file: http://www.ediy.com.my/index.php/blog/item/102-raspberry-pi-running-midori-browser-without-a-desktop
cat > /home/pi/startGhost << EOF
#!/bin/sh
xset -dpms     # disable DPMS (Energy Star) features.
xset s off       # disable screen saver
xset s noblank # don't blank the video device
unclutter &
python /home/pi/ghost-input/app.py &
matchbox-window-manager &
midori -e Fullscreen -a http://localhost:5000
EOF

# install bower stuff

# install pip
wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
sudo python get-pip.py

# install requirements
sudo pip install -r /home/pi/ghost-input/requirements.txt

# reboot
sudo reboot
