#!/bin/sh
xset -dpms     # disable DPMS (Energy Star) features.
xset s off       # disable screen saver
xset s noblank # don't blank the video device
unclutter &
matchbox-window-manager &
python ~/ghost-input/app.py &
midori -e Fullscreen -a http://localhost:5000